; ==========================================================
; GlassGarden
; PlatformIO Configuration
; ==========================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    blynkkk/Blynk
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson
    tzapu/WiFiManager  
    //2